### PR TITLE
'Update Committee Pages “governingBoard”'
Signed-off-by: Kendall Waters Perez <wendallkaters>


### PR DESCRIPTION
**Pull request by wendallkaters**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by wendallkaters** [comment]
Removed Sascha Dech from the GB page since he is no longer on the board.

**Review by iamweswilson — APPROVED** [review]
lgtm!

**Review by jamescoledesign — COMMENTED** [review]
Already merged, but looks good to me too :)

**Review by jamescoledesign — COMMENTED** [review]
Already merged, but looks good to me too :)

**Pull request merged**
