### PR TITLE
Add blog to menu and update Connect links on blog home

### PR DESCRIPTION
**Pull request by jimmytipit**
- Adds Blog to menu
- Updates "Connect" links with proper ML and Slack links

Signed-off-by: Jimmy McArthur <jimmy@tipit.net>

### CODE REVIEW

**Comment by jimmytipit** [comment]
To preview this review, please go to: https://5f9710fe7815190008bf1acf--magma-website.netlify.app/

**Comment by PARitter** [comment]
I think that the link to "docs" that you modified in blog-config.json is wrong.  It should be the same as the docs link from the in the navbar, "https://magma.github.io/magma/docs/basics/introduction.html".  As is it points to the github page for the "community" which likely is not the right result.

**Comment by jimmytipit** [comment]
@PARitter thanks and good catch! Just updated.

**Review by jbryce — APPROVED** [review]
lgtm

**Pull request merged**
