### PR TITLE
Nav logo

### PR DESCRIPTION
**Pull request by jimmytipit**
Add Magma logo to top nav

- Created new navbar logo position
- Add supporting styles for nav-brand
- Swap Discourse for Slack

### CODE REVIEW

**Comment by jbryce** [comment]
2 items (one more serious than the other):

1) The nav logo is cut off up against the left of my browser

2) Is it possible to prevent the nav logo from appearing on the homepage since there's the big hero banner style logo below it?

**Comment by jbryce** [comment]
Screen Shot 2020-09-16 at 11 30 24 AM

**Comment by jimmytipit** [comment]
What browser are you using to preview the deploy?  The Magma logo looks correct to me on FF, Chrome, Safari in all screen resolutions.  Wondering if you've got some CSS cached?

Re: making the mini-logo disappear on the homepage, that's on my list.  The way the scss is built, it's pulling in the visibility:hidden regardless.  But I've got some additional updates tied to this that I'd like to get out the door.

**Comment by jbryce** [comment]
Using Chrome on Mac. It does seem like if I maximize the window it slides over and isn't cut off anymore, so it could be resolution related. Appears correct in Safari.

I'll merge for now because the PR has a lot of good stuff and fixes in it and we can work on the logo optimization later.

**Review by jbryce — APPROVED** [review]

**Pull request merged**
